networks:
  locally:

services:
  rest:
    image: ghcr.io/rvtr/rvtrx-api-lodging:main-aspnet-rest
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=LodgingData;Username=postgres;Password=LodgingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - locally
    ports:
      - 8003:80

  data:
    environment:
      POSTGRES_PASSWORD: LodgingData@2020
    image: postgres:12
    networks:
      - locally

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9003:9411

version: '3.8'
